CMakeLists.txt: replace -std=c++11 with -std=c++17 for icu-75-1
:Release Notes:
icu-75 now requires C++17 (up from C++11) and C11 (up from C99).
https://icu.unicode.org/download/75

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/854467

ccache TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/appinstalld2/1.0.0-43/recipe-sysroot-native/usr/bin/aarch64-webos-linux/aarch64-webos-linux-g++ --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/appinstalld2/1.0.0-43/recipe-sysroot -DBOOST_BIND_NO_PLACEHOLDERS -D__STDC_FORMAT_MACROS -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/appinstalld2/1.0.0-43/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/appinstalld2/1.0.0-43/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/appinstalld2/1.0.0-43/recipe-sysrootinclude -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/appinstalld2/1.0.0-43/git/src -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/appinstalld2/1.0.0-43/build/Configured -mcpu=cortex-a72+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/appinstalld2/1.0.0-43/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fcanon-prefix-map  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/appinstalld2/1.0.0-43/git=/usr/src/debug/appinstalld2/1.0.0-43  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/appinstalld2/1.0.0-43/git=/usr/src/debug/appinstalld2/1.0.0-43  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/appinstalld2/1.0.0-43/build=/usr/src/debug/appinstalld2/1.0.0-43  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/appinstalld2/1.0.0-43/build=/usr/src/debug/appinstalld2/1.0.0-43  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/appinstalld2/1.0.0-43/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/appinstalld2/1.0.0-43/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/appinstalld2/1.0.0-43/recipe-sysroot-native=  -fvisibility-inlines-hidden -DUSE_PMLOG_DECLARATION -DENABLE_PMTRACE -DPERFLOG_USE_PMLOG -Wall -std=c++11 -Wl,--no-undefined -include TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/appinstalld2/1.0.0-43/build/Configured/webospaths.h -g -O0 -MD -MT CMakeFiles/appinstalld.dir/src/base/Locales.cpp.o -MF CMakeFiles/appinstalld.dir/src/base/Locales.cpp.o.d -o CMakeFiles/appinstalld.dir/src/base/Locales.cpp.o -c TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/appinstalld2/1.0.0-43/git/src/base/Locales.cpp
In file included from ../recipe-sysroot/usr/include/bits/libc-header-start.h:33,
                 from ../recipe-sysroot/usr/include/stdint.h:26,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/appinstalld2/1.0.0-43/recipe-sysroot-native/usr/lib/aarch64-webos-linux/gcc/aarch64-webos-linux/14.1.0/include/stdint.h:9,
                 from ../recipe-sysroot/usr/include/unicode/ptypes.h:52,
                 from ../recipe-sysroot/usr/include/unicode/umachine.h:46,
                 from ../recipe-sysroot/usr/include/unicode/utypes.h:38,
                 from ../recipe-sysroot/usr/include/unicode/locid.h:34,
                 from ../git/src/base/Locales.cpp:17:
../recipe-sysroot/usr/include/features.h:414:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  414 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
In file included from ../recipe-sysroot/usr/include/unicode/locid.h:39:
../recipe-sysroot/usr/include/unicode/localpointer.h:561:26: error: parameter declared 'auto'
  561 | template <typename Type, auto closeFunction>
      |                          ^~~~
...

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead

Change-Id: If1ad2600958c08f66d3a792db00b17c320293880
Reviewed-on: http://gpro.lge.com/c/webosose/appinstalld2/+/409714
Tested-by: Guruprasad KN <guruprasad.kn@lge.com>
Reviewed-by: Guruprasad KN <guruprasad.kn@lge.com>